Kotlin/kotlinx-benchmark

plugin/main/src/kotlinx/benchmark/gradle/JsMultiplatformTasks.kt
Adding version to NPM dependencies, because of removing possibility to set npm dependencies without version.
[KT-38683](https://youtrack.jetbrains.com/issue/KT-38683)
=> Add version to NPM dependencies

plugin/main/src/kotlinx/benchmark/gradle/BenchmarksPlugin.kt, plugin/main/src/kotlinx/benchmark/gradle/JsNodeTasks.kt, plugin/main/src/kotlinx/benchmark/gradle/JvmTasks.kt, plugin/main/src/kotlinx/benchmark/gradle/NativeMultiplatformTasks.kt, plugin/main/src/kotlinx/benchmark/gradle/Utils.kt
Gradle reports direct system properties reads as configuration cache problems as system properties are potential build configuration inputs.
See https://docs.gradle.org/7.0/userguide/configuration_cache.html for more details
=> Declare system properties reads to be compatible with Gradle configuration cache

plugin/main/src/kotlinx/benchmark/gradle/JvmTasks.kt
Hi,
This pull request attempts to fix issue #39, which causes a failure for benchmarks with complex dependencies when using Gradle 7. This issue is caused by the default `duplicatesStrategy` of the `Jar` task triggering a failure due to complex dependencies (where the same class might exist multiple times).
The solution is to update the `duplicatesStrategy` for the `jmhBenchmarkJar` tasks to exclude duplicate classes.
Fixes #39
=> Exclude duplicate classes for Jar task

examples/kotlin-multiplatform/build.gradle, integration/build.gradle.kts, integration/src/main/kotlin/kotlinx/benchmark/integration/ProjectBuilder.kt, integration/src/test/kotlin/kotlinx/benchmark/integration/ReportFormatTest.kt, integration/src/test/resources/templates/kotlin-multiplatform/build.gradle, plugin/main/src/kotlinx/benchmark/gradle/JsMultiplatformTasks.kt, plugin/main/src/kotlinx/benchmark/gradle/JsNodeTasks.kt, plugin/main/src/kotlinx/benchmark/gradle/JsSourceGeneratorTask.kt, plugin/main/src/kotlinx/benchmark/gradle/KlibResolver.kt, plugin/main/src/kotlinx/benchmark/gradle/NativeSourceGeneratorTask.kt, runtime/build.gradle
* fixes #30 (actualized #38)
* share klib resolving logic between JS IR and Native
* minor cleanup of buildscripts
* add support for JS IR in integration tests
* add support for JS IR in example
_Note: user should always specify, if they want to use IR or Legacy for running benchmarks. It will not work when specified BOTH, as target with BOTH can not have `executables`_
=> Support JS IR

README.md, examples/kotlin-multiplatform/build.gradle, integration/build.gradle.kts, integration/src/main/kotlin/kotlinx/benchmark/integration/ProjectBuilder.kt, integration/src/test/kotlin/kotlinx/benchmark/integration/ReportFormatTest.kt, integration/src/test/resources/templates/kotlin-multiplatform/build.gradle
* Add "JS IR supported" badge
* Replace "jsLegacy" naming to "js" as it is not deprecated yet and is still the default backend
=> Small improvements

runtime/commonMain/src/kotlinx/benchmark/RunnerConfiguration.kt
Error occurred when set `mode` to `avgt` according to docs.
```kotlin
benchmark {
configurations {
named("main") {
mode="avgt"
}
}
```
> Exception in thread "main" java.lang.IllegalArgumentException: No enum constant org.openjdk.jmh.annotations.Mode.avgt
But set `mode='AverageTime'` works.
In order to consist with docs, I modify the `ConfigurationReader`
=> Fix `mode` config to consist with docs

integration/src/test/resources/templates/kotlin-multiplatform/src/commonMain/kotlin/CommonBenchmark.kt, plugin/main/src/kotlinx/benchmark/gradle/SuiteSourceGenerator.kt, runtime/commonMain/src/kotlinx/benchmark/BenchmarkReportFormatter.kt
This PR adds support for parameters that contain quotation marks, such as `@Param("""a "string" with quotes""")` by improving code generation and report formatting.
=> Improve support for quotation marks in params

plugin/main/src/kotlinx/benchmark/gradle/KlibResolver.kt
JetBrains/kotlin@f8e6c59600d5ce1b4d8d69b01409764bd7010a1b introduced compatibility typealiases for classes moved to new packages. However, because both old and new packages were star-imported, we'd have ambiguity. This is fixed here.
=> Fix the unresolved reference error caused by an ambiguous reference

README.md
Thanks for creating the awesome repository. I found the wrong whitespace, so removed it.
` benchmark` -> `benchmark`
=> remove wrong whitespace in readme

plugin/main/src/kotlinx/benchmark/gradle/JvmTasks.kt
This should be enough to support building large JARs.
It prevents this error when building JARs with more than 65535 entries or larger than 4GB:
```
Execution failed for task ':mainBenchmarkJar'.
> archive contains more than 65535 entries.
```
Note that it may affect the compatibility of the JAR files with some old tools (see https://docs.gradle.org/current/dsl/org.gradle.api.tasks.bundling.Jar.html#org.gradle.api.tasks.bundling.Jar:zip64)
Fixes #95
=> Fix for building large benchmark JARs

runtime/wasmMain/src/kotlinx/benchmark/wasm/WasmBuiltInExecutor.kt
I'm trying to implement a breaking change in Kotlin/Wasm compiler that prohibits using Any in external declarations (KT-57136)
It fails with [Project] kotlinx.benchmark TC build because we use Any in external `id` function.
I'd like to merge this workaround to master and kotlin-community/dev branches. It is a bit hacky (suppresses a warning), but should work in both 1.8.x and 1.9.x.
=> [Wasm] Avoid using Any in JS interop due to KT-57136

README.md, examples/kotlin-multiplatform/build.gradle, examples/kotlin-multiplatform/src/jvmBenchmark/kotlin/JvmBenchmark.kt, integration/src/main/kotlin/kotlinx/benchmark/integration/BenchmarkTarget.kt, integration/src/main/kotlin/kotlinx/benchmark/integration/ProjectBuilder.kt, integration/src/test/kotlin/kotlinx/benchmark/integration/SourceSetAsBenchmarkTargetTest.kt, integration/src/test/resources/templates/kotlin-multiplatform/build.gradle, plugin/main/src/kotlinx/benchmark/gradle/BenchmarksExtension.kt
Fixes #111; fixes #103; fixes #70; fixes #87; fixes #71 
This PR enables using a separate source set for benchmarks in multiplatform projects. I also updated the kotlin-multiplatform example to showcase that usage.
This is technically a regression fix (commit b3d1f66) since previous versions of the plugin allowed registering multiplatform source sets. Now the behavior is to first attempt at finding a matching target (e.g. `"jvm"`) and if not found, we try to find a matching source set in all targets (this is fine because source sets defined within a target always have that target's name prefixed). It seems non-trivial to support source sets that have no associated compilation, mainly because the plugin needs a compilation for them.
Implementation note: I had to use `flatMap` and `find` …
=> Support registering multiplatform source sets as benchmark targets

runtime/commonMain/src/kotlinx/benchmark/SuiteDescriptor.kt
Addresses issue #75 by aligning the default warmup iteration time and count. The default number of warmup and measurement iterations is set to 5, and the default iteration time is set to 10 seconds, aligning with the JVM defaults.
=> Align default benchmark configurations

integration/src/main/kotlin/kotlinx/benchmark/integration/BenchmarkConfiguration.kt, integration/src/test/kotlin/kotlinx/benchmark/integration/OptionsValidationTest.kt, plugin/main/src/kotlinx/benchmark/gradle/BenchmarkConfiguration.kt, plugin/main/src/kotlinx/benchmark/gradle/Utils.kt
This PR aims to centralize the validation of all configuration values in the plugin and introducer a failure if iterationTime or iterationTimeUnit is provided without one another, as per issue #124, #125.
=> validate config values in plugin 

examples/kotlin-multiplatform/build.gradle, runtime/build.gradle
Followup to https://github.com/Kotlin/kotlinx-benchmark/pull/163
=> Enable default template hierarchy

examples/kotlin-multiplatform/build.gradle, integration/src/test/kotlin/kotlinx/benchmark/integration/InvalidTargetingTest.kt, integration/src/test/resources/templates/invalid-target/wasm-nodejs/build.gradle, integration/src/test/resources/templates/invalid-target/wasm-nodejs/src/commonMain/kotlin/CommonBenchmark.kt, plugin/main/src/kotlinx/benchmark/gradle/JsEngineExecTasks.kt, runtime/jsMain/src/kotlinx/benchmark/js/JsBenchmarkExecutor.kt, runtime/jsMain/src/kotlinx/benchmark/js/JsBuiltInExecutor.kt
Followup to https://github.com/Kotlin/kotlinx-benchmark/pull/165
=> Support nodejs() environment for wasmJs

integration/src/test/kotlin/kotlinx/benchmark/integration/GradleTest.kt, integration/src/test/kotlin/kotlinx/benchmark/integration/JvmToolchainsTest.kt, integration/src/test/kotlin/kotlinx/benchmark/integration/testDsl.kt, integration/src/test/resources/templates/kmp-with-toolchain/build.gradle, integration/src/test/resources/templates/kmp-with-toolchain/gradle.properties, integration/src/test/resources/templates/kmp-with-toolchain/settings.gradle, integration/src/test/resources/templates/kmp-with-toolchain/src/commonMain/kotlin/CommonBenchmark.kt, plugin/main/src/kotlinx/benchmark/gradle/JmhBytecodeGeneratorTask.kt, plugin/main/src/kotlinx/benchmark/gradle/JvmTasks.kt, plugin/main/src/kotlinx/benchmark/gradle/Utils.kt
Gradle tasks configured to run JVM benchmarks didn't use the project's Java toolchain and instead used the same Java executables as the Gradle did. That could lead to a scenario when the project had a Java toolchain with a higher version than the version of Java Gradle was launched with. In such a scenario benchmark compilation would fail.
This PR brings toolchain awareness to related Gradle tasks.
Fixes #176
=> Use toolchains for java tasks

docs/configuration-options.md
Followup to https://github.com/Kotlin/kotlinx-benchmark/pull/167
=> Add a guide to benchmark configuration options

docs/configuration-options.md, docs/tasks-overview.md
Followup to https://github.com/Kotlin/kotlinx-benchmark/pull/168
=> Add a guide to tasks created by the plugin

README.md, docs/separate-benchmark-source-set.md
Followup to https://github.com/Kotlin/kotlinx-benchmark/pull/170
=> Add a guide to creating a separate module for benchmarks

README.md, docs/kotlin-jvm-project-setup.md
Followup to https://github.com/Kotlin/kotlinx-benchmark/pull/175
=> Add a guide to setting up Kotlin/JVM and Java projects for benchmarking

docs/writing-benchmarks.md
Followup to https://github.com/Kotlin/kotlinx-benchmark/pull/182
=> Add a guide to writing benchmarking

plugin/main/src/kotlinx/benchmark/gradle/Utils.kt
This method has been deprecated and calls to System.getProperty are handle correctly
See https://docs.gradle.org/8.5/userguide/upgrading_version_7.html#for_use_at_configuration_time_deprecation
=> Remove use of forUseAtConfigurationTime

integration/src/test/resources/templates/kmp-with-toolchain/build.gradle
Otherwise, the latest Kotlin Gradle Plugin (2.0) fails with: "Configuring JVM toolchain in the Kotlin target level DSL is prohibited. JVM toolchain feature should be configured in the extension scope as it affects all JVM targets (JVM, Android)."
It is necessary to move these changes to `master` branch to simplify the support of `kotlin-community/dev` branch. As well as simplifying the future migration of the project to a new version of the compiler.
=> Configure jvmToolchain in the `kotlin` extension scope

integration/src/test/resources/templates/kmp-with-toolchain/gradle.properties, integration/src/test/resources/templates/kotlin-multiplatform/gradle.properties
The option MaxPermSize option triggers an error on my machine:
```text
Caused by: org.gradle.api.GradleException: Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/8.0.2/userguide/gradle_daemon.html
...
Please read the following process output to find out more:
-----------------------
Unrecognized VM option 'MaxPermSize=2048m'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
=> remove MaxPermSize from gradle.properties in test templates

buildSrc/build.gradle.kts, buildSrc/settings.gradle.kts
- buildSrc is (basically) an independent Gradle build, and each Gradle build should have a settings.gradle.kts.
- Use centralized repository definitions.
(Note: Maven Central is defined before GPP so that Gradle will search MC first, and MC tends to be more stable.)
=> Add settings.gradle.kts into buildSrc

plugin/main/src/kotlinx/benchmark/gradle/JmhBytecodeGeneratorTask.kt, plugin/main/src/kotlinx/benchmark/gradle/JsSourceGeneratorTask.kt, plugin/main/src/kotlinx/benchmark/gradle/NativeSourceGeneratorTask.kt, plugin/main/src/kotlinx/benchmark/gradle/WasmSourceGeneratorTask.kt
`@InputFiles` with `@PathSensitive(PathSensitivity.RELATIVE)` makes it impossible to reuse build cache between builds with different build numbers because a jar name includes build number.
https://youtrack.jetbrains.com/issue/KTI-1801/benchmarksmainBenchmarkGenerate-cant-use-build-cache-from-builds-with-different-build-number
=> Use `Classpath` normalization for classpath inputs of `JmhBytecodeGeneratorTask`

docs/configuration-options.md, integration/src/test/kotlin/kotlinx/benchmark/integration/KotlinNativeTest.kt, integration/src/test/resources/templates/kotlin-native/build.gradle, integration/src/test/resources/templates/kotlin-native/gradle.properties, integration/src/test/resources/templates/kotlin-native/src/commonMain/kotlin/CommonBenchmark.kt, integration/src/test/resources/templates/kotlin-native/src/nativeMain/kotlin/DebugBenchmark.kt, plugin/main/src/kotlinx/benchmark/gradle/BenchmarkConfiguration.kt, plugin/main/src/kotlinx/benchmark/gradle/NativeMultiplatformTasks.kt
Adds a build type setting to the NativeBenchmarkTarget to provide the ability to test debug builds. Fixes #189
=> Support debug build configuration for K/N

build.gradle, gradle.properties, gradle/libs.versions.toml, integration/build.gradle.kts, plugin/build.gradle, plugin/gradle.properties, runtime/build.gradle
Using a Version Catalog helps with sharing dependencies and aligning versions between different projects.
This is particularly useful because Benchmarks uses Included Builds, and Version Catalogs make it easy to make sure the same dependencies are used in each project.
Notes:
- The version of binary-compatibility-validator was `0.15.0-Beta.1` in the root build, but `0.15.0-Beta.2` in the Benchmark Gradle Plugin build. I had to choose the lower version, because `0.15.0-Beta.2` requires a newer version of Gradle.
- The `kotlinx.team.infra` plugin does not have a published Gradle Plugin Marker, so it has to use the legacy plugin application method (buildscript classpath).
=> Use Gradle Version Catalog for defining dependencies and versions

.teamcity/utils.kt
Currently, tasks are not scheduled to macOS agents as agents either don't have JDK16 installed, or are Apple Sillicon-based.
This PR overwrites corresponding tunables to unlock execution on macOS agents.
=> Tune some kotlin-team-infra plugin parameters to unlock execution on macOS agents

plugin/build.gradle, plugin/main/src/kotlinx/benchmark/gradle/AnnotationsValidator.kt, plugin/main/src/kotlinx/benchmark/gradle/BenchmarksExtension.kt, plugin/main/src/kotlinx/benchmark/gradle/BenchmarksPlugin.kt, plugin/main/src/kotlinx/benchmark/gradle/JmhBytecodeGeneratorWorker.kt, plugin/main/src/kotlinx/benchmark/gradle/JsSourceGeneratorTask.kt, plugin/main/src/kotlinx/benchmark/gradle/KlibResolver.kt, plugin/main/src/kotlinx/benchmark/gradle/NativeSourceGeneratorTask.kt, plugin/main/src/kotlinx/benchmark/gradle/SuiteSourceGenerator.kt, plugin/main/src/kotlinx/benchmark/gradle/Utils.kt, plugin/main/src/kotlinx/benchmark/gradle/WasmSourceGeneratorTask.kt, plugin/main/src/kotlinx/benchmark/gradle/internal/BenchmarkDependencies.kt, plugin/main/src/kotlinx/benchmark/gradle/internal/KotlinxBenchmarkPluginInternalApi.kt, plugin/main/src/kotlinx/benchmark/gradle/internal/generator/RequiresKotlinCompilerEmbeddable.kt, plugin/main/src/kotlinx/benchmark/gradle/internal/generator/workers/GenerateJsSourceWorker.kt, plugin/main/src/kotlinx/benchmark/gradle/internal/generator/workers/GenerateWasmSourceWorker.kt, runtime/commonMain/src/kotlinx/benchmark/internal/KotlinxBenchmarkPluginInternalApi.kt
Use Worker API to generate benchmark code
- Update the Benchmark JS/Wasm/Native source generation tasks to use the Worker API, so that `kotlin-compiler-embeddable` can be a compileOnly dependency, thus resolving https://youtrack.jetbrains.com/issue/KT-66764
- Create `GenerateJsSourceWorker` and `GenerateWasmSourceWorker` for isolating the JS and Wasm generation code. 
- Updated the Js/Wasm/Native generation tasks to invoke the source generators in a Worker isolated classpath.
- Created a new Configuration for declaring `kotlin-compiler-embeddable`, and pass it to the Js/Wasm/Native generation tasks. 
- Create a BenchmarkDependencies utility for defining all Configurations used in the plugin. (This also lays the groundwork for unifying the JMH version …
=> Use Worker API for Benchmark generators

build.gradle, gradle/libs.versions.toml, plugin/build.gradle, settings.gradle
Add a dependency constraint in the root project to allow overriding the Kotlin version.
The Kotlin version is not overridden in the Benchmark Gradle plugin - this should use the version of Kotlin embedded into Gradle.
Add a check to ensure that the version is overridden.
=> Add Kotlin version override

gradle/libs.versions.toml
This is required to ensure compatibility of the build with Kotlin 2.1+ after resolving https://youtrack.jetbrains.com/issue/KT-61706
=> Bump binary-compatibility-validator to 0.16.2

.teamcity/additionalConfiguration.kt, .teamcity/pom.xml, .teamcity/settings.kts, .teamcity/utils.kt
=> Show TeamCity build status in Kotlinx Benchmark GitHub PRs

build.gradle, plugin/api/kotlinx-benchmark-plugin.api, plugin/main/src/kotlinx/benchmark/gradle/BenchmarksPlugin.kt, runtime/api/kotlinx-benchmark-runtime.klib.api
Also, update the dump to reflect the actual state of the Gradle plugin. Reorders entries in the dumps: https://github.com/Kotlin/binary-compatibility-validator/pull/225, https://github.com/Kotlin/binary-compatibility-validator/issues/196 Removes internal constants from the dump: https://github.com/Kotlin/binary-compatibility-validator/issues/90 Fixes #248
=> Introduce a workaround for apiCheck similar to apiDump

plugin/main/src/kotlinx/benchmark/gradle/NativeMultiplatformTasks.kt
Hi,
I was a bit confused with the current warning when the native benchmark is skipped because the current OS does not match the expected for that target
E.g.:
> Skipping benchmarks for 'iosArm64' because they cannot be run on current OS: Expected linux_x64, but was ios_arm64
It sounds more like _target **iosArm64** expects **linux_x64** but the current OS is **ios_arm64**_
If you change the expected and actual values it would be more clear. Please, let me know what you think.
If you disagree feel free to close the PR)
=> Switch expected and actual values in warning for native tasks

plugin/main/src/kotlinx/benchmark/gradle/NativeSourceGeneratorTask.kt
Relates to [KT-65285](https://youtrack.jetbrains.com/issue/KT-65285)
Fixes integration tests with Kotlin that contains this feature
=> Add support for non-packed klib files in the native generator

plugin/main/src/kotlinx/benchmark/gradle/NativeMultiplatformTasks.kt
... by using `associateWith` instead of manually wiring up compile outputs back to the `implementation` dependency of the benchmark compilation.
Tested using the `kotlinx.io` project. 
**Before**:
**After**:
=> Fix Native Benchmark Compilations triggering compile tasks on Gradle sync

buildSrc/src/main/kotlin/KotlinCommunity.kt, integration/build.gradle.kts, integration/src/main/kotlin/kotlinx/benchmark/integration/Runner.kt
This is needed for building the library as a part of TeamCity aggregate builds.
=> Forward the kotlin.native.version parameter to test projects

.teamcity/additionalConfiguration.kt
Such a build configuration is useful for catching new changes that are not compatible with the latest Kotlin build.
For details see https://youtrack.jetbrains.com/articles/KT-A-297/Libraries-develop-and-Kotlin-master-checks
=> Add a TC build config for building with Kotlin master

runtime/build.gradle.kts
It is necessary to use NPM related subtarget to be compatible with examples/kotlin-multiplatform. D8 is subtarget without necessity in NPM.
=> Use nodejs for wasmJs target

integration/src/test/kotlin/kotlinx/benchmark/integration/KotlinJsTest.kt, integration/src/test/kotlin/kotlinx/benchmark/integration/ProjectWithResourceFilesTest.kt, integration/src/test/kotlin/kotlinx/benchmark/integration/TransitiveDependenciesResolutionTest.kt, integration/src/test/resources/templates/es-modules/build.gradle, integration/src/test/resources/templates/es-modules/gradle.properties, integration/src/test/resources/templates/es-modules/src/commonMain/kotlin/CommonBenchmark.kt, integration/src/test/resources/templates/project-with-resources/build.gradle, integration/src/test/resources/templates/project-with-resources/gradle.properties, integration/src/test/resources/templates/project-with-resources/src/commonMain/kotlin/CommonBenchmark.kt, integration/src/test/resources/templates/project-with-resources/src/commonMain/resources/dummy.file.txt, integration/src/test/resources/templates/transitive-dependencies-resolution/build.gradle, integration/src/test/resources/templates/transitive-dependencies-resolution/gradle.properties, integration/src/test/resources/templates/transitive-dependencies-resolution/library/build.gradle, integration/src/test/resources/templates/transitive-dependencies-resolution/library/src/commonMain/kotlin/library.kt, integration/src/test/resources/templates/transitive-dependencies-resolution/settings.gradle, integration/src/test/resources/templates/transitive-dependencies-resolution/src/commonMain/kotlin/CommonBenchmark.kt, plugin/main/src/kotlinx/benchmark/gradle/JsEngineExecTasks.kt, plugin/main/src/kotlinx/benchmark/gradle/JsMultiplatformTasks.kt, plugin/main/src/kotlinx/benchmark/gradle/NativeMultiplatformTasks.kt, plugin/main/src/kotlinx/benchmark/gradle/WasmMultiplatformTasks.kt, runtime/jsMain/src/kotlinx/benchmark/NodeJsEngineSupport.kt, runtime/jsMain/src/kotlinx/benchmark/js/JsBenchmarkExecutor.kt
Following issues revealed in #185 were addressed:
- dependency resolution problem was fixed so now there's no need to explicitly specify all transitive dependencies;
- having files in a resource directory no longer fail compilation;
- benchmarks compilation now inherit module kind from the main compilation.
Closes #185
=> Fix assorted problems with K/JS projects

gradle/libs.versions.toml
Update kotlinx.team.infra to a version that no longer provides native targets and source-set setup functionality that is incompatible with KGP 2.2+.
=> Update kotlinx.team.infra plugin

integration/src/test/kotlin/kotlinx/benchmark/integration/BenchmarkFunctionNameValidationTest.kt, integration/src/test/resources/templates/funny-names/build.gradle, integration/src/test/resources/templates/funny-names/gradle.properties, integration/src/test/resources/templates/funny-names/src/commonMain/kotlin/CommonBenchmark.kt, plugin/main/src/kotlinx/benchmark/gradle/JmhBytecodeGeneratorWorker.kt
It seems like there's no so much we can do with invalid Java identifiers being used as function names at the time Kotlin code is already compiled and is about to be processed to generate JMH benchmarks. So instead of trying to work it around, let's report the problem and let users to fix it themselves.
Closes #272
=> Check if benchmark names are legal Java names on JVM

.teamcity/utils.kt
Existing settings result in using amd64-JDK on arm64 macOS agents (via rosetta).
=> Use platform agnostic env variable with the JDK

docs/configuration-options.md, examples/java/build.gradle.kts, examples/kotlin-jvm-separate-benchmark-source-set/build.gradle.kts, examples/kotlin-jvm/build.gradle.kts, examples/kotlin-multiplatform/build.gradle, gradle/libs.versions.toml, integration/src/test/kotlin/kotlinx/benchmark/integration/JmhVersionValidationTest.kt, integration/src/test/resources/templates/conflicting-jmh-versions/build.gradle, integration/src/test/resources/templates/conflicting-jmh-versions/gradle.properties, plugin/build.gradle.kts, plugin/main/src/kotlinx/benchmark/gradle/BenchmarkConfiguration.kt, plugin/main/src/kotlinx/benchmark/gradle/BenchmarksPlugin.kt, plugin/main/src/kotlinx/benchmark/gradle/JvmJavaTasks.kt, plugin/main/src/kotlinx/benchmark/gradle/JvmMultiplatformTasks.kt, plugin/main/src/kotlinx/benchmark/gradle/Utils.kt
If a project explicitly uses an older JMH version, the plugin will warn about it.
If there are multiple JVM targets configured with different JMH versions, the plugin will warn about an unsupported setup.
Closes #147
=> Updated default JMH version to 1.37 and added its validation

build.gradle.kts, integration/src/main/kotlin/kotlinx/benchmark/integration/ProjectBuilder.kt
It was decided to deprecate and phase out the concept (see KT-77721).
=> [KUP] Disable opt-in Kotlin compiler warnings

plugin/main/src/kotlinx/benchmark/gradle/BenchmarkConfiguration.kt
project.findProperty is not Gradle project isolation compatible (https://docs.gradle.org/current/userguide/isolated_projects.html) because it attempts to read properties from parent projects, thus violating project isolation.
Instead, moving to project.providers.gradleProperty that does not have this behavior.
Fixes https://github.com/Kotlin/kotlinx-benchmark/issues/258
=> Make Gradle plugin isolation compatible
